apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/jenkins_home
  volumeMode: Filesystem
